version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.21
    ports:
      - 80:80
    volumes:
      - ./:./var/www
      - ./default-conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
      - pgadmin
    networks:
      - app-bridge

  flask:
    container_name: flask
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 "app.create_app:create_app()"
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      app-bridge:
        aliases:
          - flask-app

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=databasename

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=ABC
      - PGADMIN_DEFAULT_PASSWORD=ABC
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555

networks:
  app-bridge:


volumes:
  data:
    driver: local
  postgres_data:
